from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = true
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"
pre_bump_hooks = [
  "echo 'define(__major__, {{version.major}})' > src/version.m4",
  "echo 'define(__minor__, {{version.minor}})' >> src/version.m4",
  "echo 'define(__patch__, {{version.patch}})' >> src/version.m4",
]
post_bump_hooks = []
pre_package_bump_hooks = [
  "echo 'define(__{{package}}_major__, {{version.major}})' > version.m4",
  "echo 'define(__{{package}}_minor__, {{version.minor}})' >> version.m4",
  "echo 'define(__{{package}}_patch__, {{version.patch}})' >> version.m4",
]
post_package_bump_hooks = []

[git_hooks]

[commit_types]
chore = { omit_from_changelog = true }
ci = { omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "JiƒÅn", username = "coolDudeRude" },
  { signature = "Jian", username = "coolDudeRude" },
]

[bump_profiles]

[packages]
libdirectives = { path = "src/libdirectives", public_api = true }
